major algorithmic update to rsa_noise_ceiling.py
cvnlab/GSN pull request #4
Opened 2022-05-03 05:50 UTC by jacob-prince

- ported recent commits from matlab implementation to python - major revamp of rsa_noise_ceiling.py to incorporate recent updates to the algorithm (e.g. split half procedures, plotting)
- fixed bug in calc_shrunken_covariance that was causing incorrect shrinkage values to be selected if any negative log likelihood values were nan
- added relevant files to utilities.py
- i have tested the new implementation by verifying that it provides the same outputs as the matlab implementation given the same input data (up to a few decimal places- there is randomness built into the pipeline so outputs will not be numerically identical). plot outputs also look virtually identical. 
- this implementation has not been fully edge-cased and may be subject to bugs outside of the main use cases - should test further when possible.

2022-05-03 18:35 UTC, kendrickkay requested changes
I looked through.  Generally looks good.  A few remarks:

I see that you did "nll[p] = np.inf" --> it's a little hacky.  I think you should at least update the docstring to mention that it can be inf (and not nan, which is what is mentioned from the matlab documentation).
 
For an additional test of Matlab vs Python, can you try running the first few lines of
~/Dropbox/rsanoiseceiling/code.development/GSNunittests.py
(where we load data from "testdataFFA50.mat") and seeing if similar results are obtained?

2022-05-03 18:37 UTC, kendrickkay commented
Also, bear in mind that I think Ian ported some utilities (for GLMsingle), so in a sense you duplicated effort:

GLMsingle/glmsingle/cod/calc_cod.py 
GLMsingle/glmsingle/utils/zerodiv.py 

I wonder if his port and your port are equally good/right.  Interesting...

In theory you could use his ports instead of yours if you wanted to consolidate..   Up to you how you want to handle this

2022-05-03 19:34 UTC, kendrickkay commented
Also, the "internal inputs" docstring part --- this was not intended to be exposed to the user (that's why the MATLAB version has an extra line before this part).  Can you hide that from the doc string (maybe an extra line)?

2022-05-03 19:35 UTC, kendrickkay commented
And, a general question:  Was your port intended to be an **exact** port?  Was there any part where things seemed iffy?  For example, those utility functions might have been hairy to get **exactly** identical, maybe?

2022-05-03 21:29 UTC, jacob-prince commented
- re: the use of np.inf, yes i will definitely update the docstring.
- thanks for pointing out the testdataFFA50 case, i will run that and report back via slack.
- re: the utility functions, i directly copied Ian's implementations of calc_cod and zerodiv, so to the extent to which his implementations are solid for GLMsingle, they shouldn't pose problems for GSN. i implemented squish, posrect, and nanreplace myself. i think these three functions are relatively straightforward - hopefully no issues there. 
- will definitely hide the internal inputs from the user. 
- i tried to go for an exact port, but there are probably slight divergences. for example, i didn't implement errorbar2.m in python so that component of the plotting routine is missing. in at least one other place, i used a different data structure than you did for convenience (e.g. a dictionary vs. a cell array) or had to modify an implementation detail (e.g. in python you can't dynamically expand an array by adding a value to the end+kth row, so the expansions of datasplitr and modelsplitr required concatenating new empty matrices to the existing matrices. i don't think these slight details would cause any divergent noise ceiling estimates - overall, i was shooting for an "exact" port up to the limit of whatever is randomized within the pipeline. however, i'm pretty sure i could find a bug (or multiple) if i tried hard enough via edge casing or passing weird/unexpected inputs. will inevitably discover these as we move forward.

2022-05-03 23:21 UTC, kendrickkay commented
ok sounds good. 

But it seems like plotting error bars would be a good idea.  No rush, maybe you can just open a new Issue.

2024-02-25 20:03 UTC, jacob-prince commented
this pull request is outdated. closing.

2024-02-25 20:03 UTC, closed without merging